repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.14
    hooks:
      - id: uv-sync
      - id: uv-lock
      - id: uv-export
        args: [--no-hashes]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=51200"]
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.11
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --fix-only]
      # Run the formatter.
      - id: ruff-format
